### ISSUE TITLE
Typo on Canvas render only, not in corresponding README.md

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/python-p3-oo-counting-sentences-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/209747?module_item_id=483953

### Concern

The heading of the last section on the page is misspelled "Reesources"

### Suggested Changes

Fix typo to be "Resources"

**Comment by professor-ben** [comment]
I believe this is fixed now. Not quite sure what happened in the first place but thanks for bringing it to our attention!
