### ISSUE TITLE
Suggested Addition to Instructions

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/python-p3-oo-counting-sentences-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236174?module_item_id=554094

### Concern

In the instructions for this lab, particularly for the "count_sentences()" section, there is somewhat crucial information missing regarding what defaults are required to make the tests pass.

### Additional Context

After making all tests pass aside from the "count_sentences()" tests, I spent quite a while trying a variety of solutions before eventually looking to the solution.  After literally copying and pasting before working backwards to recreate it, the tests still didn't pass.  Fast forward another 30+ minutes the cause was the requirement in the tests to give a default value to the initialization (which I gave a default of a string previously, as the errors seemed to want).  As it turns out the default value needed to be an empty string, which I can't find noted anywhere in the lab or test files.

### Suggested Changes

Since the tests require the possibility of an empty string returning 0 as the number of sentences, it would be very helpful to include that, at least in the test files so the alerts are more specific.

**Comment by professor-ben** [comment]
Hi Connor,

I think that's a good point. I'll try and get this fixed later this week.

Thanks,
Ben

**Comment by professor-ben** [comment]
Just pushed a fix to clarify. Thanks again for the report.

-Ben
